[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"

[functions."notif-scadenze"]
  schedule = "@daily"

[functions."mail-notify"]
  schedule = "*/30 * * * *"

[functions."telegram-morning-digest"]
  schedule = "0 6 * * *"
